import { Router } from 'express';
import authRoutes from './auth.routes';
import healthRoutes from './health.routes';
import brandsRoutes from './brands.routes';
import suppliersRoutes from './suppliers.routes';
import warehousesRoutes from './warehouses.routes';
import attributesRoutes from './attributes.routes';
import featuresRoutes from './features.routes';
import categoriesRoutes from './categories.routes';
import catalogSettingsRoutes from './catalog-settings.routes';
import facetedNavigationRoutes from './faceted-navigation.routes';
import uploadRoutes from './upload.routes';
import productsRoutes from './products.routes';
import measurementRulesRoutes from './measurement-rules.routes';
import seoSettingsRoutes from './seo-settings.routes';
import generalSettingsRoutes from './general-settings.routes';
import richSnippetsSettingsRoutes from './rich-snippets-settings.routes';
import importTemplatesRoutes from './import-templates.routes';
import productImportRoutes from './product-import.routes';
import imageSizeTemplateRoutes from './image-size-template.routes';
import customersRoutes from './customers.routes';
import couriersRoutes from './couriers.routes';
import emailTemplatesRoutes from './email-templates.routes';
import orderStatusesRoutes from './order-statuses.routes';
import ordersRoutes from './orders.routes';
import reviewsRoutes from './reviews.routes';
import productQaRoutes from './product-qa.routes';
import wishlistsRoutes from './wishlists.routes';
import blogRoutes from './blog.routes';

const router: Router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/brands', brandsRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/warehouses', warehousesRoutes);
router.use('/attributes', attributesRoutes);
router.use('/features', featuresRoutes);
router.use('/categories', categoriesRoutes);
router.use('/catalog-settings', catalogSettingsRoutes);
router.use('/faceted-navigation', facetedNavigationRoutes);
router.use('/upload', uploadRoutes);
router.use('/products', productsRoutes);
router.use('/measurement-rules', measurementRulesRoutes);
router.use('/seo-settings', seoSettingsRoutes);
router.use('/general-settings', generalSettingsRoutes);
router.use('/rich-snippets-settings', richSnippetsSettingsRoutes);
router.use('/import-templates', importTemplatesRoutes);
router.use('/product-import', productImportRoutes);
router.use('/design/image-sizes', imageSizeTemplateRoutes);
router.use('/design/email-templates', emailTemplatesRoutes);
router.use('/customers', customersRoutes);
router.use('/couriers', couriersRoutes);
router.use('/order-statuses', orderStatusesRoutes);
router.use('/orders', ordersRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/product-qa', productQaRoutes);
router.use('/wishlists', wishlistsRoutes);
router.use('/blog', blogRoutes);

export default router;
