CREATE TABLE IF NOT EXISTS "similar_products_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"module_enabled" boolean DEFAULT true NOT NULL,
	"default_limit" integer DEFAULT 12 NOT NULL,
	"cache_duration" integer DEFAULT 900 NOT NULL,
	"exclude_out_of_stock" boolean DEFAULT true NOT NULL,
	"same_category_enabled" boolean DEFAULT true NOT NULL,
	"same_category_limit" integer DEFAULT 8 NOT NULL,
	"same_category_title" varchar(255) DEFAULT 'Продукти от същата категория' NOT NULL,
	"same_category_sort" varchar(50) DEFAULT 'popularity' NOT NULL,
	"same_category_match_type" varchar(50) DEFAULT 'primary_only' NOT NULL,
	"same_category_show_image" boolean DEFAULT true NOT NULL,
	"same_category_show_price" boolean DEFAULT true NOT NULL,
	"same_category_show_add_to_cart" boolean DEFAULT true NOT NULL,
	"similar_features_enabled" boolean DEFAULT true NOT NULL,
	"similar_features_limit" integer DEFAULT 8 NOT NULL,
	"similar_features_title" varchar(255) DEFAULT 'Продукти с подобни характеристики' NOT NULL,
	"similar_features_min_similarity" integer DEFAULT 30 NOT NULL,
	"similar_features_show_score" boolean DEFAULT false NOT NULL,
	"similar_features_fallback" varchar(50) DEFAULT 'same_category' NOT NULL,
	"similar_features_combine_with_same_category" boolean DEFAULT false NOT NULL,
	"similar_features_show_image" boolean DEFAULT true NOT NULL,
	"similar_features_show_price" boolean DEFAULT true NOT NULL,
	"similar_features_show_add_to_cart" boolean DEFAULT true NOT NULL,
	"related_enabled" boolean DEFAULT true NOT NULL,
	"related_limit" integer DEFAULT 6 NOT NULL,
	"related_title" varchar(255) DEFAULT 'Свързани продукти' NOT NULL,
	"related_bidirectional" boolean DEFAULT false NOT NULL,
	"related_priority" varchar(50) DEFAULT 'high' NOT NULL,
	"related_show_image" boolean DEFAULT true NOT NULL,
	"related_show_price" boolean DEFAULT true NOT NULL,
	"related_show_add_to_cart" boolean DEFAULT true NOT NULL,
	"layout_type" varchar(50) DEFAULT 'grid' NOT NULL,
	"grid_columns" integer DEFAULT 4 NOT NULL,
	"card_style" varchar(50) DEFAULT 'standard' NOT NULL,
	"show_section_dividers" boolean DEFAULT true NOT NULL,
	"animation" varchar(50) DEFAULT 'fade' NOT NULL,
	"mobile_layout" varchar(50) DEFAULT 'same' NOT NULL,
	"excluded_category_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"excluded_product_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"max_candidates" integer DEFAULT 100 NOT NULL,
	"enable_query_caching" boolean DEFAULT true NOT NULL,
	"module_order" jsonb DEFAULT '["related","similar_features","same_category"]'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
